[amenity.Sustenance]
bar = "Bar is a purpose-built commercial establishment that sells alcoholic drinks to be consumed on the premises. They are characterised by a noisy and vibrant atmosphere, similar to a party"
biergarten = "Biergarten or beer garden is an open-air area where alcoholic beverages along with food is prepared and served. A biergarten can commonly be found attached to a beer hall, pub, bar, or restaurant."
cafe = "Cafe is generally an informal place that offers casual meals and beverages; typically, the focus is on coffee or tea. Also known as a coffeehouse, bistro or sidewalk cafe."
fast_food = "Fast food restaurant."
food_court = "An area with several different restaurant food counters and a shared eating area. Commonly found in malls, airports, etc."
ice_cream =	"Ice cream shop or ice cream parlour. A place that sells ice cream and frozen yoghurt over the counter"
pub = "A place selling beer and other alcoholic drinks; may also provide food or accommodation (UK)."
restaurant = "Restaurant."

[amenity.Education]
college = "Campus or buildings of an institute of Further Education (aka continuing education)"
dancing_school = "A dancing school or dance studio"
driving_school = "Driving School which offers motor vehicle driving lessons"
first_aid_school = "A place where people can go for first aid courses."
kindergarten = "For children too young for a regular school (also known as preschool, playschool or nursery school), in some countries including afternoon supervision of primary school children."
language_school = "Language School: an educational institution where one studies a foreign language."
library = "A public library (municipal, university, ...) to borrow books from."
surf_school = "A surf school is an establishment that teaches surfing."
toy_library = "A place to borrow games and toys, or play with them on site."
research_institute = "An establishment endowed for doing research."
training = "Public place where you can get training."
music_school = "A music school, an educational institution specialized in the study, training, and research of music."
school = "School and grounds - primary, middle and seconday schools"
traffic_park = "Juvenile traffic schools"
university = "A university campus: an institute of higher education"

[amenity.Transportation]
bicycle_parking = "Parking for bicycles"
bicycle_repair_station = "General tools for bicycle repairs"
bicycle_rental = "Place where individuals can borrow bicycles"
bicycle_wash = "Clean a bicycle"
boat_rental = "Place where individuals can borrow a boat"
boat_sharing = "Share a Boat"
bus_station = "bus station."
car_rental = "Place where individuals can borrow cars"
car_sharing = "Share a car"
car_wash =	"Wash a car"
compressed_air = "A device to inflate tires/tyres (e.g. motorcar, bicycle)"
vehicle_inspection = "Government vehicle inspection"
charging_station =  "Charging facility for electric vehicles"
driver_training = "A place for driving training on a closed course"
ferry_terminal = "Ferry terminal/stop. A place where people/cars/etc. can board and leave a ferry."
fuel = "Petrol station; gas station; marine fuel; ..."
grit_bin = "A container that holds grit or a mixture of salt and grit."
motorcycle_parking = "Parking for motorcycles"
parking = "Car park."
parking_entrance = "An entrance or exit to a parking facility."
parking_space =	"A single parking space."
taxi = "A place where taxis wait for passengers."
weighbridge = "A large weight scale to weigh vehicles and goods"

[amenity.Financial]
atm = "ATM or cash point: a device that provides access to financial transactions."
payment_terminal = "Self-service payment kiosk/terminal"
bank =	"Bank or credit union: a financial establishment where customers can deposit and withdraw money, take loans, make investments and transfer funds."
bureau_de_change = "Bureau de change, money changer, currency exchange, Wechsel, cambio – a place to change foreign bank notes and travellers cheques."
money_transfer = "A place that offers money transfers, especially cash to cash"
payment_centre = "A non-bank place, where people can pay bills of public and private services and taxes."

[amenity.Healthcare]
baby_hatch = "A place where a baby can be anonymously left."
clinic = "A medium-sized medical facility or health centre."
dentist = "A dentist practice / surgery."
doctors = "A doctor's practice / surgery."
hospital = "A hospital providing in-patient medical treatment."
nursing_home = "A home for disabled or elderly persons who need permanent care."
pharmacy = "Pharmacy: a shop where a pharmacist sells medications"
social_facility = "A facility that provides social services: group & nursing homes, workshops for the disabled, homeless shelters, etc."
veterinary = "A place where a veterinary surgeon, also known as a veterinarian or vet, practices."

[amenity.Entertainment_or_Arts_and_Culture]
arts_centre = "A venue where a variety of arts are performed or conducted"
brothel = "An establishment specifically dedicated to prostitution"
casino = "A gambling venue with at least one table game (e.g. roulette, blackjack) that takes bets on sporting and other events."
cinema = "A place where films are shown (US: movie theater)"
community_centre = "A place mostly used for local events, festivities and group activities."
conference_centre = "A large building that is used to hold a convention"
events_venue = "A building specifically used for organising events"
exhibition_centre = "An exhibition centre"
fountain = "A fountain for cultural / decorational / recreational purposes."
gambling = "A place for gambling. (includes bingo and pachinko)"
love_hotel = "A love hotel is a type of short-stay hotel operated primarily for the purpose of allowing guests privacy for sexual activities."
music_venue = "An indoor place to hear live music."
nightclub = "A place to drink and dance (nightclub). The German word is 'Disco' or 'Discothek'."
planetarium = "A planetarium."
public_bookcase = "A freely accessible cabinet or shelf located where people can borrow, take, or leave books"
social_centre = "A place for free activities."
stage = "A raised platform for performers."
stripclub = "A place that offers striptease or lapdancing"
studio_area = "TV radio or recording studio"
swingerclub = "A club where people meet to have a party and group sex."
theatre = "A theatre or opera house where live performances occur, such as plays, musicals and formal concerts."

[amenity.Public_Service]
courthouse = "A building home to a court of law, where justice is dispensed"
fire_station = "A station of a fire brigade"
police = "A police station where police officers patrol from and that is a first point of contact for civilians"
post_box = "A box for the reception of mail."
post_depot = "Post depot or delivery office, where letters and parcels are collected and sorted prior to delivery."
post_office = "Post office building with postal services"
prison = "A prison or jail where people are incarcerated before trial or after conviction"
ranger_station = "National Park visitor headquarters: official park visitor facility with police, visitor information, permit services, etc"
townhall = "Building where the administration of a village, town or city may be located, or just a community meeting place"

[amenity.Facilities]
bbq = "BBQ or Barbecue is a grill for cooking food, typically used outdoors. May be found in city parks or at beaches."
bench =  "A bench to sit down and relax a bit"
dog_toilet = "Area designated for dogs to urinate and excrete."
dressing_room = "Area designated for changing clothes."
drinking_water = "A place where humans can obtain potable water for consumption. Also known as a drinking fountain or bubbler."
give_box = "A small facility where people drop off and pick up various types of items in the sense of free sharing and reuse."
mailroom = "A mailroom for receiving packages or letters."
parcel_locker = "Machine for picking up and sending parcels"
shelter = "A small shelter against bad weather conditions."
shower = "Public shower."
telephone = "Public telephone"
toilets = "Public toilets (might require a fee)"
water_point = "Place where you can get large amounts of drinking water"
watering_place = "Place where water is contained and animals can drink"

[amenity.Waste_Management]
sanitary_dump_station = "A place for depositing human waste from a toilet holding tank."
recycling = "Recycling facilities."
waste_basket = "A single small container for depositing garbage that is easily accessible for pedestrians."
waste_disposal = "A medium or large disposal bin, typically for bagged up household or industrial waste."
waste_transfer_station = "A waste transfer station is a location that accepts, consolidates and transfers waste in bulk."

[amenity.other]
animal_boarding = "A facility where you can bring your animal for a limited period of time"
animal_breeding = "A facility where animals are bred, usually to sell them"
animal_shelter = "A shelter that recovers animals in trouble"
animal_training = "A facility used for non-competitive animal training"
baking_oven = "An oven used for baking bread and similar, for example inside a bakehouse."
clock = "A public visible clock"
crematorium = "A place where dead human bodies are burnt"
dive_centre = "A dive center is the base location where sports divers usually start scuba diving or make dive guided trips at new locations."
funeral_hall = "A place for holding a funeral ceremony."
grave_yard = "A place of burial, often you'll find a church nearby."
hunting_stand = "A hunting stand: an open or enclosed platform used by hunters"
internet_cafe =	"A place whose principal role is providing internet services to the public."
kitchen = "A public kitchen in a facility to use by everyone or customers"
kneipp_water_cure = "Outdoor foot bath facility. Usually this is a pool with cold water and handrail."
lounger = "An object for people to lie down."
marketplace = "A marketplace where goods and services are traded daily or weekly."
monastery = "Monastery is the location of a monastery or a building in which monks and nuns live."
mortuary = "A morgue or funeral home, used for the storage of human corpses."
photo_booth = "A stand to create instant photos."
place_of_mourning = "A room or building where families and friends can come, before the funeral, and view the body of the person who has died."
place_of_worship = "A church, mosque, or temple"
public_bath = "A location where the public may bathe in common, etc. japanese onsen, turkish bath, hot spring"
public_building = "A generic public building."
refugee_site = "A human settlement sheltering refugees or internally displaced persons"
vending_machine = "A machine selling goods – food, tickets, newspapers, etc."